name: portfolio
description: My new Flutter Portfolio
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_image_slider: ^0.0.2
  flutter_image_slideshow: ^0.1.6
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.18.0
  responsive_framework: ^0.1.4

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/svgs/
    - assets/lotties/
    - assets/app_icons/
    - assets/map_styles/
    - assets/fonts/
  fonts:
  - family: notosan
    fonts:
      - asset:	assets/fonts/NotoSansKhmer_VariableFont.ttf

  uses-material-design: true
  generate: true